name: nepali_date_picker
description: Material Style Date Picker with Bikram Sambat(Nepali) Calendar Support. Supports Android, iOS and Fuchsia. Available in Nepali and English Languages.
version: 2.0.0+1
author: Sarbagya Dhaubanjar <sarbagyastha@gmail.com>
homepage: https://github.com/sarbagyastha/nepali_date_picker

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nepali_utils: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: